### ISSUE TITLE
Reliese with DBAL: Parse error: syntax error, unexpected 'const'

### ISSUE THREAD

**Issue by metrey** [reliese/laravel#100]
When run:
```
php artisan code:models
```

Got error as:
```
In Connection.php line 64:

  Parse error: syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE)
```
As far, I checked, it's on **Connection.php** of **Doctrine\DBAL**

I use:

- "reliese/laravel": "^0.0.13"
- "doctrine/dbal": "^2.5",

**Comment by CristianLlanos** [comment]
More information to replicate the issue is needed. The issue can be reopened provided that there is more info about it.
