### ISSUE TITLE
 ErrorException  : count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by plutobit** [reliese/laravel#102]
```
ErrorException  : count(): Parameter must be an array or an object that implements Countable

  at /Users/jackie/Workspace/vendor/sound/ezs-api-laravel/vendor/reliese/laravel/src/Coders/Model/Model.php:684
    680|      * @return bool
    681|      */
    682|     public function hasCustomPrimaryKey()
    683|     {
  > 684|         return count($this->primaryKeys->columns) == 1 &&
    685|                $this->getPrimaryKey() != $this->getDefaultPrimaryKeyField();
    686|     }
    687|
    688|     /**

  Exception trace:

  1   count()
      /Users/jackie/Workspace/vendor/sound/ezs-api-laravel/vendor/reliese/laravel/src/Coders/Model/Model.php:684

  2   Reliese\Coders\Model\Model::hasCustomPrimaryKey()
      /Users/jackie/Workspace/vendor/sound/ezs-api-laravel/vendor/reliese/laravel/src/Coders/Model/Factory.php:309
```

**Comment by tposcic** [comment]
Yeah same issue here

**Comment by ARKKYN** [comment]
same isssue here

**Comment by fringesurfer** [comment]
Same here and I have 60 tables to model ...

**Comment by ARKKYN** [comment]
@tposcic , @fringesurfer , @plutobit please use master branch for temporary solution

**Comment by BrenoRRodrigues** [comment]
Its problem, happen when any table don't have a primary key...

I solved add column id with primary key and auto increment.. in table with this problem...


But.. i am searching for other solution for this trouble...

**Comment by mrpiagg** [comment]
I have changed the code in vendor/reliese/laravel/src/Coders/Model/Model.php:684 to:
public function hasCustomPrimaryKey()
{
return **isset($this->primaryKeys->columns) &&** count($this->primaryKeys->columns) == 1 && $this->getPrimaryKey() != $this->getDefaultPrimaryKeyField();
}

It seems to be working fine.

**Comment by garywoodfine** [comment]
Would be great if you could implement a feature on the  code:make models method whereby you could exclude a list of table you don't want to generate models for.

`php artisan code:models  --except tablename1, tablename2`

I was getting the reported error because my schema incluides the Auth Generated password_resets table which doesn't include a primary key

**Comment by CristianLlanos** [comment]
Sure! You can do it by adding each table name in the `except` key in the [config file](https://github.com/reliese/laravel/blob/master/config/models.php#L283).

**Comment by garywoodfine** [comment]
@CristianLlanos thank you so much!  I now realize,  this is perfect. Appreciate the time taken to answer.  It has pointed me in the direction for another question I had.  Only been playing with this for an hour or so still a bit too learn, but so far this is a really great addition to my workflow.  Thanks guys!

 The old RTFM answer! :-)

**Comment by lk77** [comment]
same error on laravel fresh install, with  php 7.2

**Comment by estimtrack** [comment]
@lk77 i solved it adding:
`$table->increments('id');`
to the table _password_resets_

**Comment by cartes** [comment]
My problem was that the fillable was a string, You must to use it as an array. Ex:

public $filable = ["variable_key"];
