### ISSUE TITLE
Table Prefixes

### ISSUE THREAD

**Issue by jr-smith** [reliese/laravel#103]
Doesn't work well with table prefixes. Will load the migrations table and add the prefix to the class (which is unncessary).

**Comment by CristianLlanos** [comment]
It's an interesting feature. I encourage you guys, to make a pull request adding the feature.

**Comment by CristianLlanos** [comment]
I'm closing this issue, since it's supported in the development version of this package.

**Comment by FrodeMMeling** [comment]
Where can I find the development version of this package? I only find "master" branch.

**Comment by FrodeMMeling** [comment]
@CristianLlanos Is there a doc or wiki describing how to use table prefixes?

**Comment by FrodeMMeling** [comment]
TIP! You need to republish `php artisan vendor:publish --tag=reliese-models` to get updated models.php file with new features.

to enable prefixes from .env, add to .env:
`DB_TABLE_PREFIX=myDBprefix_`

Add/Modify to config/databases.php:
`'prefix' => env('DB_TABLE_PREFIX', ''),`

Then add/modify to reliese file:
`'table_prefix' => 'env('DB_TABLE_PREFIX', '')',`
