### ISSUE TITLE
Invalid Argument supplied for foreach

### ISSUE THREAD

**Issue by priestd09** [reliese/laravel#11]
Laravel 5.3 
I am getting an Invalid Argument supplied for foreach error when using php artisan code:models

I traced it back to Models line 1036

I fixed it by checking if primaryKeys->columns is an array before processing the foreach block
Updated code is below

Please confirm and add this possible fix if you want.
```php
public function isPrimaryKey(Fluent $command)
    {
        if(is_array($this->primaryKeys->columns)){

            foreach ($this->primaryKeys->columns as $column) {
                if (! in_array($column, $command->columns)) {
                    return false;
                }
            }

        }

        return true;
    }
```

**Comment by CristianLlanos** [comment]
I'll check it out. Thanks :sweat_smile:

**Comment by CristianLlanos** [comment]
Where you able to trace back in which of your tables this error happened? If so, would you mind sharing its structure with me? Does it have a primary key? No problem if you can't. Thanks in advance :+1:

**Comment by priestd09** [comment]
I tracked it to a table that didn't have a primary key
I confirmed by adding a primary key of id and I removed the aforementioned fix and no errors occurred
When I removed that primary key, then the error happened again.
I hope this helps
