### ISSUE TITLE
Create model from a second database connection

### ISSUE THREAD

**Issue by alextesi** [reliese/laravel#112]
I tried your code and it works very well.
I think that when we create models from a second database connection then you have to insert in each model the database connection used to create it.

like this:
protected $connection = 'mysql2';

if you chosen to skip this for any reason can you please explain me.
Thanks
Alessandro

**Comment by CristianLlanos** [comment]
It makes good sense to do that. However, not all projects have this need; that's why I made it configurable. So, if you need this feature, just set the configuration accordingly. Look at the [models configuration file](https://github.com/reliese/laravel/blob/master/config/models.php#L86).

**Comment by CristianLlanos** [comment]
I'm closing this issue, since the package do support this feature. Thanks for your feedback.

**Comment by alextesi** [comment]
thank you very much for your answer.
