### ISSUE TITLE
Issue by generate models

### ISSUE THREAD

**Issue by avratny** [reliese/laravel#13]
Hello,

i´m getting this error, when I try to generate the models:

`Call to undefined method Illuminate\Database\MySqlConnection::setFetchMode()`

Maybe you can help me?!

Thank you very much!

**Comment by jkpatel291289** [comment]
getting same error 

jay@jay-desktop:/var/www/laravelprojects/larabox.dev$ php artisan code:models
PHP Fatal error:  Call to undefined method Illuminate\Database\MySqlConnection::setFetchMode() in /var/www/laravelprojects/larabox.dev/vendor/reliese/laravel/src/Meta/MySql/Schema.php on line 64

jay@jay-desktop:/var/www/laravelprojects/larabox.dev$ php artisan -V
Laravel Framework 5.4.6

**Comment by CristianLlanos** [comment]
Ir seems that method is no longer available in Laravel 5.4 :( I'll see if there is another way to make this work.

**Comment by avratny** [comment]
Wow that would be great ;) Thank you!

**Comment by CristianLlanos** [comment]
Hi, guys. Sorry for the delay. It's been a very busy week for me.
I've just added a quick fix for this. Hope it works again for you. Please don't hesitate to contact me again if you find my package is not working properly. Thanks :)
