### ISSUE TITLE
How to auto generate accessors & mutators

### ISSUE THREAD

**Issue by raunak-gupta** [reliese/laravel#132]
Hi,

Is there any option to auto generate Accessors & Mutators (_getter setter_) by using `php artisan code:models` command ?

Like

```
public function getFirstNameAttribute($value)
{
    return $value;
}

public function setFirstNameAttribute($value)
{
    $this->attributes['first_name'] = $value;
}
```

after this is generated user can then modified it according to their need.

**Comment by CristianLlanos** [comment]
There is an undocumented way to add mutators to your generated models. The Factory class has a `public function mutate()` method which will let you achieve it.
