### ISSUE TITLE
Enhancement: custom Model names

### ISSUE THREAD

**Issue by elymatos** [reliese/laravel#138]
It can useful for some use cases to have a option to modelName instead of just tableName. For example, I have some tables like auth_user, auth_group, etc but I want my model to be called by domain names, like User, Group, etc.

**Comment by jerryliu306** [comment]
me too!!!

**Comment by jerryliu306** [comment]
> It can useful for some use cases to have a option to modelName instead of just tableName. For example, I have some tables like auth_user, auth_group, etc but I want my model to be called by domain names, like User, Group, etc

can you resolved?

**Comment by jerryliu306** [comment]
@elymatos can you resolved ?

**Comment by gareth-ib** [comment]
@elymatos  create it as an config/options driven feature. if you do, please PR it to my fork  https://github.com/pursehouse/modeler-laravel-eloquent

**Comment by CristianLlanos** [comment]
You can trim a prefix to achieve that: https://github.com/reliese/laravel/blob/master/config/models.php#L310
