### ISSUE TITLE
Fork maintained

### ISSUE THREAD

**Issue by Atiladanvi** [reliese/laravel#140]
Comment here if you know what fork are maintained and is passive PRs

**Comment by gareth-ib** [comment]
mine is, and I'd love more people to join in  https://github.com/pursehouse/modeler-laravel-eloquent

**Comment by nasatome** [comment]
@Atiladanvi you've already tested your project and it's working properly  https://github.com/pursehouse/modeler-laravel-eloquent

**Comment by Atiladanvi** [comment]
Nice! i will change my composer files.
