### ISSUE TITLE
Table with field on type "Time" not working

### ISSUE THREAD

**Issue by MarceloPetrucio** [reliese/laravel#141]
Hi guys, I have an error with my generated models, when my table has a field in type "Time" it is understanding as type "Data" and when I go to run the model it returns me the following error:

"Unexpected data found. Unexpected data found. Data missing"

But if I pick up and change the "time" field of the Dates array and put it in the Times array in the model, it works fine.

Part of code in generated model before changes (not working):
```	
protected $dates = [
	'hour_initial'
];

protected $times = [];
```

Part of code in generated model after changes (working):
```
protected $dates = [];

protected $times = [
        'hour_initial'
];
```

Need to verify in the code generation when it is a field of type "time" it does not put in the array of dates and yes of the eloquent team array, has anyone ever gone through it?

**Comment by CristianLlanos** [comment]
This is weird. Does Eloquent support the `$times` property? You might be using another tool based on Eloquent.
