### ISSUE TITLE
Super Slow when dbhost contains multiple (unused) schemata

### ISSUE THREAD

**Issue by fiveDust** [reliese/laravel#146]
schema and/or table name should be performed without analyzing all other possibly existing schematas. Example : I have schema specified in connection prop in env or app config, overridable by console args. Now, every attempt to create a model , even if only for one single table, parses ALL schematas that are existing on the db host. I have 20 concurrent DBs here and a simple model generation takes up to 15 seconds! 

Culprit is in the Factory. Schema and table have to be filtered for here already : 
$this->models->on($connection)->create($schema, $table);

This poses also another issue, when one of the other schematas, that have nothing to do with the laravel app in question, have an issue, like in my example there was an orphan table cached in one of those dbs, which throws an exception  Illuminate\Database\QueryException with message 'SQLSTATE[42S02]: Base table or view not found and breaks the whole generator process. 

Not sure why this is done the way it is, but for performance and error-reduction reasons, it should only analyse / parse the schema defined in connection and command args.

**Comment by gareth-ib** [comment]
I know one issue is that foreign keys can at any time need data from another schema. If you'd like to work on restructuring the system to dynamically follow those potential needs instead of pre-gathering them, I'd be interested in accepting it into my fork at https://github.com/pursehouse/modeler-laravel-eloquent

**Comment by fiveDust** [comment]
"I know one issue is that foreign keys can at any time need data from another schema." ... I haven't thought about that. In most cases that should not be a concern. Maybe allow that as an option with the tradeoff of having a much improved speed. Will need to give it some more thought.

**Comment by CristianLlanos** [comment]
Exactly, that's the reason I made the algorithm scan all possible tables. Just to make sure all foreign keys are properly processed. However, you can always tell it to scan only one schema or table at a time:
```bash
php artisan code:models --schema=shop
```
