### ISSUE TITLE
Not working with Laravel 6.0

### ISSUE THREAD

**Issue by fiveDust** [reliese/laravel#147]
composer : "reliese/laravel": "^0.0.13" 
->
Your requirements could not be resolved to an installable set of packages.
->
reliese/laravel v0.0.13 requires illuminate/filesystem ~5.1 - 
...
Can only install one of: laravel/framework[6.0.x-dev, 5.8.x-dev]

**Comment by mateullull** [comment]
+1

**Comment by nasatome** [comment]
+1

**Comment by awfatechglobal** [comment]
+1

**Comment by MarceloPetrucio** [comment]
+ 1

**Comment by mvdgeijn** [comment]
+1

**Comment by Takashi-Fujie** [comment]
+1

**Comment by anselim** [comment]
+1

**Comment by lk77** [comment]
Hello,
this is still an issue one month later,
is this package still supported ?

we have no other choice but drop the use of this package of all our projets.

**Comment by fiveDust** [comment]
> Hello,
> this is still an issue one month later,
> is this package still maintained ?
> 
> we have no other choice but drop the use of this package of all our projets.

ditto. One way around it would be to have a dummy 5.8 installation pointing to the same db for the only purpose of model generation, then copying them over. Should work as the relevant Eloquent API hasn't changed to produce any colliding effects.

**Comment by lk77** [comment]
@fiveDust using :
```
"laravel/framework": "^6.2 as 5.8"
```

could be a temporary solution in dev environments.

**Comment by estimtrack** [comment]
I have the same issue :S

 Problem 1
    - Installation request for reliese/laravel ^0.0.13 -> satisfiable by reliese/laravel[v0.0.13].
    - Conclusion: remove laravel/framework v6.3.0

**Comment by SoulMate94** [comment]
+1

**Comment by gareth-ib** [comment]
my fork is fine with Laravel 6  https://github.com/pursehouse/modeler-laravel-eloquent
I'm eagerly hoping for contributors to help me continue this fine project

**Comment by nasatome** [comment]
@gareth-ib  I was about to make a comment referencing your project, I hope more people are encouraged and support you to keep it.

**Comment by geone** [comment]
Hello guys, I have created another branch for this package which only has the composer.json laravel upgrades here: https://github.com/geone/reliaseV6Support and you can download this package via composer in https://packagist.org/packages/reliese-laravel-v6/laravel if in the future the owner of this package upgrade this to v6 feel free to let me know and I will cancel this repository.

**Comment by gareth-ib** [comment]
@geone that's already been done in the above mentioned fork. Would be better to help improve a maintained fork than create another fork

**Comment by geone** [comment]
Hi @gareth-ib 

Thank you for your reply, 
I understand you do have a fork from that project, but the detail is that it as a different namespace from  Reliese\<whateverPath> and I do need to have the same namespace as   Reliese\<whateverPath>  in the current project I'm working, since I'm extending functionality. :P

**Comment by gareth-ib** [comment]
@geone ah gotcha, well the Reliese one doesn't seem like it'll ever continue again, so that's just postponing the inevitable :) And if your extensions are good, it might be nice to get them into the central codebase

**Comment by CristianLlanos** [comment]
Hi, guys. Sorry for taking so long to update the package. Support has been added for Laravel 6 and many features have been tagged with it.
