### ISSUE TITLE
Model name truncated

### ISSUE THREAD

**Issue by IManAsap** [reliese/laravel#148]
Tables whose names end with 'ches' generate a truncated  name.

Example :

"php artisan code:models --table=document_taches" generate DocumentTach.php with "Class DocumentTach"

Config :
"laravel/framework": "5.8.*"
"reliese/laravel": "^0.0.13"

**Comment by juventus18** [comment]
is this a lang issue? in English -es is generally a plural form, that is why the ending is dropped here (i.e. this is expected behavior).

**Comment by gareth-ib** [comment]
probably need to disabled plural
```php
'pluralize' => false
```
in your config

**Comment by CristianLlanos** [comment]
As a convention, model names are treated as singular. That's why it changed the table name.
