### ISSUE TITLE
mkdir(): Invalid path

### ISSUE THREAD

**Issue by pqthang97** [reliese/laravel#15]
I'm using laravel 5.4.9 & reliese newest version to fix fetch...
but i have issue when run 

php artisan code:models

> [ErrorException]
>   mkdir(): Invalid path
> 

I tried create folder Models in App, but still error

**Comment by CristianLlanos** [comment]
Would you mind sharing the contents of storage/logs/Laravel.log of your project when this error happens, please? So I will be able to see what the error is. Thanks.

**Comment by pqthang97** [comment]
`[2017-02-06 10:40:07] local.ERROR: exception 'ErrorException' with message 'mkdir(): Invalid path' in C:\wamp64\www\advisor\vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php:435
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'mkdir(): Invali...', 'C:\\wamp64\\www\\a...', 435, Array)
#1 C:\wamp64\www\advisor\vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php(435): mkdir('', 493, true)
#2 C:\wamp64\www\advisor\vendor\reliese\laravel\src\Coders\Model\Factory.php(379): Illuminate\Filesystem\Filesystem->makeDirectory('', 493, true)
#3 C:\wamp64\www\advisor\vendor\reliese\laravel\src\Coders\Model\Factory.php(150): Reliese\Coders\Model\Factory->modelPath(Object(Reliese\Coders\Model\Model), Array)
#4 C:\wamp64\www\advisor\vendor\reliese\laravel\src\Coders\Model\Factory.php(118): Reliese\Coders\Model\Factory->create('advisor', 'migrations')
#5 C:\wamp64\www\advisor\vendor\reliese\laravel\src\Coders\Console\CodeModelsCommand.php(69): Reliese\Coders\Model\Factory->map('advisor')
#6 [internal function]: Reliese\Coders\Console\CodeModelsCommand->handle()
#7 C:\wamp64\www\advisor\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(29): call_user_func_array(Array, Array)
#8 C:\wamp64\www\advisor\vendor\laravel\framework\src\Illuminate\Support\helpers.php(912): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#9 C:\wamp64\www\advisor\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(86): value(Object(Closure))
#10 C:\wamp64\www\advisor\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(30): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#11 C:\wamp64\www\advisor\vendor\laravel\framework\src\Illuminate\Container\Container.php(524): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#12 C:\wamp64\www\advisor\vendor\laravel\framework\src\Illuminate\Console\Command.php(182): Illuminate\Container\Container->call(Array)
#13 C:\wamp64\www\advisor\vendor\symfony\console\Command\Command.php(262): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#14 C:\wamp64\www\advisor\vendor\laravel\framework\src\Illuminate\Console\Command.php(168): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#15 C:\wamp64\www\advisor\vendor\symfony\console\Application.php(826): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 C:\wamp64\www\advisor\vendor\symfony\console\Application.php(189): Symfony\Component\Console\Application->doRunCommand(Object(Reliese\Coders\Console\CodeModelsCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 C:\wamp64\www\advisor\vendor\symfony\console\Application.php(120): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 C:\wamp64\www\advisor\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(123): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 C:\wamp64\www\advisor\artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 {main}  
`

**Comment by CristianLlanos** [comment]
Sorry to ask, but did you publish the config file correctly with `php artisan vendor:publish --tag=reliese-models`?

**Comment by pqthang97** [comment]
Thank you, i run `php artisan vendor:publish --tag=reliese-models` and it work fine.

**Comment by CristianLlanos** [comment]
Happy to help! 😄

**Comment by devalexandre** [comment]
I trying use a 

php artisan code:models


 mkdir(): Invalid path 

but don't work

**Comment by er-chaan** [comment]
test
