### ISSUE TITLE
Reliese trying to access a database not in the .env config

### ISSUE THREAD

**Issue by seanatdss** [reliese/laravel#156]
Hello:

I am attempting to use the tool in an environment where multiple mysql databases are under one mysql instance and my credentials do not have access to all the databases.  In the .env file I am setting the db_database to the specific database I want to use ('mysae') but when I run php artisan code:models it throws a PDO exception because it does not have access to the database named 'les'.  

'Les' is another database inside the instance but I don't have credentials to access it.  The error message specifically says it is trying to do a 'SHOW FULL COLUMNS'  on a table inside the 'les' database - but I just want it to scan the mysae database I set in the DB_DATABASE field and it should ignore the les database.

Any pointers for how to proceed here?

Thank you.

**Comment by CristianLlanos** [comment]
This package has been designed to read all your available mysql schemas to keep track of cross schema relationships. It defaults to reading everything and for it not to fail, you should have access to all of them. I'm sorry for not being able to help you here.
