### ISSUE TITLE
Table with Multiple relationships to One table

### ISSUE THREAD

**Issue by chorton** [reliese/laravel#16]
I have a table that has two fields where those two fields are associated with the same column from one other table.  When the models get generated, the eloquent relationship only creates one of them, not both.

How can I make sure that both get created, or is this a bug or currently something that is not yet supported?

Example:

Account
---Id
....

Asset
---Id (pkid)
---AccountId (contains an account id - foreign key on this column referencing Account.Id)
---ResellerId (contains an account id - foreign key on this column referencing Account.Id)
....

**Comment by CristianLlanos** [comment]
I think this is a bug. It should figure out all those relationships 🤔 I'll check into it.

**Comment by solokingjec** [comment]
Thanks for this awesome tool. I am also facing the same problem.
![screenshot from 2017-03-05 10-54-20](https://cloud.githubusercontent.com/assets/6312641/23585518/2a36c33c-0192-11e7-84c6-53f42f3a9e0e.png)

**Comment by qeifar** [comment]
Did you already solved it?

**Comment by CristianLlanos** [comment]
No, I haven't. This one is kind of tricky. There are two (or more) relationships and I don't know how to choose the name of the relationship in order not to overlap the previous ones. I might need to ask the developer for each of their relationship names which makes this task very difficult.

**Comment by CristianLlanos** [comment]
I'm open for suggestions and/or pull requests to solve this problem :) Thanks, guys.

**Comment by DamienBurkeJJ** [comment]
@CristianLlanos the problem is that you're naming the relationships after the tables being referred to rather than using the name of the foreign key. E.g. for the above example we'd want two relationships, called `account` and `reseller` rather than getting confused about having two called account.

It might - haven't investigated in depth - be as simple as changing the `name()` method in BelongsTo.php and HasOne.php to use `$this->foreignKey()` (and then strip any trailing `_id` or `id` from the field name) instead of `$this->related->getClassName()`

**Comment by CristianLlanos** [comment]
🤔 It might do. The thing is not all of us have databases using this convention. We might also need to think about their use cases as well, imo.

**Comment by DamienBurkeJJ** [comment]
Really? It's a very common convention; how about having it as the default behaviour with a config option to use the previous behaviour?

**Comment by CristianLlanos** [comment]
It is, for new projects (most of them). What about legacy ones or projects being migrated to Laravel with existing database? :D Nevertheless, I agree, we can keep the default behaviour for them.

**Comment by boukeversteegh** [comment]
#66 Here is my pull request for this feature
