### ISSUE TITLE
Not selecting the DB in env

### ISSUE THREAD

**Issue by dansleboby** [reliese/laravel#161]
Hi,
When I run 
`php artisan code:models`

It dosen't take the "DB_DATABASE" it try to fech other databases. Because the user I set have access to many DB.

When I change the user to have only one DB it was fine

**Comment by CristianLlanos** [comment]
Hi, it’s not clear what the problem is. Are you asking why this package reads all of your MySQL schemas when you only specified one? If so, this behaviour is intentional. It’s been designed this way so that it can keep track of cross schema relationships.

**Comment by dansleboby** [comment]
Ok I unserstand,
I think you should make a warning or tell it on read-me this thing:
Be aware of stric mode, we scan all database.

Because I have some of my DB of older project where it not compatible with strict mode so I get error like this:
```
SQLSTATE[42000]: Syntax error or access violation: 1055 '***.***.***' isn't in GROUP BY (SQL: SHOW FULL COLUMNS FROM `***`.`****`)
```
