### ISSUE TITLE
'except' configuration setting needs prefixes

### ISSUE THREAD

**Issue by tpaksu** [reliese/laravel#164]
Hi again,

When I use table names without the prefix, the `except` array is ignored. If I add the prefix to every table name in that array, it works as expected. I suppose it should hande the prefix internally? The `only` array might have the same logic.

**Comment by CristianLlanos** [comment]
The except array was not designed with the `prefix` feature in mind https://github.com/reliese/laravel/blob/master/src/Coders/Model/Factory.php#L130. PRs are welcome, thanks.

**Comment by tpaksu** [comment]
@CristianLlanos do you think the prefix configuration should also be taken from the database configuration?

**Comment by CristianLlanos** [comment]
I'm not sure whether I understand what you mean :thinking:. When you say "database configuration" you mean `config/database.php`?

**Comment by tpaksu** [comment]
@CristianLlanos yes I meant that.

**Comment by CristianLlanos** [comment]
It's a fair point. I'm not sure whether that `prefix` field in `config/database.php` is used for the same purpose as our `table_prefix` in `config/models.php`. However, you are welcome to contribute with pull requests ;)
