### ISSUE TITLE
Too few arguments error when using BlameableBehavior 

### ISSUE THREAD

**Issue by lugotal** [reliese/laravel#171]
When using BlameableBehavior in the generated models, saving a model fails as creating() in WhoDidIt expects two arguments - event and model - to be passed but is only called with one.

Using Laravel 7.4.5

**Comment by CristianLlanos** [comment]
The Observer API appears to have been changed https://laravel.com/docs/7.x/eloquent#observers. Thanks for reporting it. If you'd like, you can make a pull request with the upgrade.
