### ISSUE TITLE
vendor/reliese/laravel/src/Coders/Model/Factory.php:297 

### ISSUE THREAD

**Issue by KlissmanGranados** [reliese/laravel#173]
When executing: php artisan code: models
an exception is thrown:

  Undefined offset: 0

  at vendor/reliese/laravel/src/Coders/Model/Factory.php:297
    293▕             if (! preg_match($namespacePattern, $usedClass)) {
    294▕                 
    295▕                     //Do not import classes with same name of className
    296▕                     preg_match('/\\\\[^\\\\]*$/', $usedClass, $matches, PREG_OFFSET_CAPTURE, 0);
  ➜ 297▕                     $usedClassName = str_replace("\\","",$matches[0][0]);
    298▕ 
    299▕                     if($usedClassName != $className){
    300▕                         $result[] = "use {$usedClass};";
    301▕                     }

      +18 vendor frames 
  19  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()

**Comment by CristianLlanos** [comment]
Thanks for reporting the bug. Unfortunately, there is not enough information to replicate it. If you find a fix, feel free to make a pull request to share it with the community.

**Comment by Shi974** [comment]
Same issue here. Been using this useful package for months now and first time getting this error, or an error generally speaking.

php artisan code:models --table=dispositifs

   ErrorException

  Undefined offset: 0

  at C:\laragon\www\admin-portail\vendor\reliese\laravel\src\Coders\Model\Factory.php:297
    293|             if (! preg_match($namespacePattern, $usedClass)) {
    294|
    295|                     //Do not import classes with same name of className
    296|                     preg_match('/\\\\[^\\\\]*$/', $usedClass, $matches, PREG_OFFSET_CAPTURE, 0);
  > 297|                     $usedClassName = str_replace("\\", "", $matches[0][0]);
    298|
    299|                     if($usedClassName != $className){
    300|                         $result[] = "use {$usedClass};";
    301|                     }

  1   C:\laragon\www\admin-portail\vendor\reliese\laravel\src\Coders\Model\Factory.php:297
      Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Undefined offset: 0", "C:\laragon\www\admin-portail\vendor\reliese\laravel\src\Coders\Model\Factory.php")

  2   C:\laragon\www\admin-portail\vendor\reliese\laravel\src\Coders\Model\Factory.php:272
      Reliese\Coders\Model\Factory::formatUsedClasses("Dispositif")

**Comment by VladimirBerdnik** [comment]
@Shi974 , could you please debug the code and show us what values variables `$className` and `$usedClass` have?

**Comment by Dezaimasu** [comment]
Think I found why this happens.

I checked `$usedClasses` values on crash, all strings in the array were single words, like `User`, `Post`, `Order`, etc.
No namespaces at all, so the regexp failed. 

https://laravel.com/docs/8.x/releases#laravel-8

> In previous releases of Laravel, the RouteServiceProvider contained a $namespace property. This property's value would automatically be prefixed onto controller route definitions and calls to the action helper / URL::action method. In Laravel 8.x, this property is null by default. This means that no automatic namespace prefixing will be done by Laravel. Therefore, in new Laravel 8.x applications, controller route definitions should be defined using standard PHP callable syntax:

I probably tinkered something else as well, but after setting `$namespace` in `RouteServiceProvider` to previous `'App\Http\Controllers'` value everything worked fine. Either that or it just cache clearing :)

**Comment by thomasdseao** [comment]
I think it is happened because you haven't published the configuration files (models.php) from the package.
Please read the doc : 
- composer require ...
- Add the service provider to your config/app.php ...
- php artisan vendor:publish --tag=reliese-models ....
