### ISSUE TITLE
Class 'Doctrine\DBAL\Driver\PDOMySql\Driver' not found

### ISSUE THREAD

**Issue by aavinseth** [reliese/laravel#178]
After updating to Laravel 8.14 having this issue when running `php artisan code:models` command

**Comment by akinsayo** [comment]
In composer.json, add "doctrine/dbal": "^2.5" if not on the list or change to ^2.5 if greater than, then run composer update

**Comment by aavinseth** [comment]
@akinsayo I have tried installing doctrine/dbal which update to 3.0 but still having the same problem

Class 'Doctrine\DBAL\Driver\PDOMySql\Driver' not found

  at D:\xampp\htdocs\project\vendor\laravel\framework\src\Illuminate\Database\MySqlConnection.php:89
     85▕      * @return \Doctrine\DBAL\Driver\PDOMySql\Driver
     86▕      */
     87▕     protected function getDoctrineDriver()
     88▕     {
  ➜  89▕         return new DoctrineDriver;
     90▕     }
     91▕ }
     92▕

  1   D:\xampp\htdocs\project\vendor\laravel\framework\src\Illuminate\Database\Connection.php:894
      Illuminate\Database\MySqlConnection::getDoctrineDriver()

  2   D:\xampp\htdocs\project\vendor\reliese\laravel\src\Meta\MySql\Schema.php:273
      Illuminate\Database\Connection::getDoctrineSchemaManager()

**Comment by akinsayo** [comment]
Install 2.5

**Comment by CristianLlanos** [comment]
I've tried on a fresh Laravel install (v8.17.2) with Doctrine Dbal (3.0) and works fine. Open the thread again if you find more information to replicate it.
