### ISSUE TITLE
Parent on users table

### ISSUE THREAD

**Issue by IManAsap** [reliese/laravel#182]
Hello

My table has the name 'users',

If I use the following configuration

    ...
    'transpeapppla' => [
    
        'users' => [
            'parent' => Illuminate\Foundation\Auth\User::class,
        ],
    ]
    ...

I get the following model

    class User extends User
    {
        protected $table = 'users';
    ...
    }

With the following logical message

    Class 'App\Models\Base\User' not found

Is that a bug?

**Comment by CristianLlanos** [comment]
Can you show the full User class and also the resulting path?

**Comment by CristianLlanos** [comment]
Fixed on version v0.0.19

**Comment by IManAsap** [comment]
Thanks
