### ISSUE TITLE
Laravel 5.4

### ISSUE THREAD

**Issue by Atles** [reliese/laravel#19]
I have try this with the new laravel and it didn't work.
Do you know why? Can you fix it?

**Comment by CristianLlanos** [comment]
I'll check it out 🤔

**Comment by qeifar** [comment]
I already tried on laravel 5.4, and it works awesomely.. But I am a lil bit confused why when i call an Artisan from controllers it shows this result
![sxa](https://cloud.githubusercontent.com/assets/13729734/26084572/b40cf0f8-3a0f-11e7-949c-2bce13001234.PNG)

**Comment by CristianLlanos** [comment]
This package is working without problems in Laravel 5.4. I've tested this with a fresh install of Laravel.
