### ISSUE TITLE
Removing Laravel package discovery from composer.json

### ISSUE THREAD

**Issue by CristianLlanos** [reliese/laravel#197]
Even tough, [this functionality](https://laravel.com/docs/8.x/packages#package-discovery) is very handy when installing the package, we should not force the use of this package on a production system. I may be wrong here, but I think that's exactly what that feature does: registers the package even on production. Security-wise it should probably be better to have this package as a development dependency only.

I'm opening this issue to let you guys know about this concerning feature. Fixing it from this package is as easy as removing [some lines](https://github.com/reliese/laravel/blob/v1.x/composer.json#L47) from the composer file. But I'd like to hear more opinions on this.

**Comment by nasatome** [comment]
Maybe just add a general instruction comment, explaining the use of "--no-dev", as far as I know that avoids that problem, but if not then suggestions are welcome :D

`--no-dev: Skip installing packages listed in require-dev. The autoloader generation skips the autoload-dev rules.`

In Production deploy: 
Optional fix for composer install only: rm -rf ./vendor
`composer install --no-dev --optimize-autoloader`

**Comment by CristianLlanos** [comment]
Makes total sense. Thanks, @nasatome, you rock!
