### ISSUE TITLE
Error when running php artisan code:models

### ISSUE THREAD

**Issue by activemonkeys** [reliese/laravel#2]
Thanks for providing this nice package. Installed it on a fresh 5.3 installation with MySQL + Laravel Boilerplate by Anthony Rappa. 

All migrations run normally however after running: php artisan code:models the following errors appear (same goes for scaffolding a specific table while running php artisan code:models --table=users)

Would be nice to receive a suggestion on where I can best start looking to resolve this issue

 [Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for t
  he right syntax to use near '53' at line 1 (SQL: SHOW TABLES FROM 53)

  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for t
  he right syntax to use near '53' at line 1

  [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for t
  he right syntax to use near '53' at line 1

**Comment by CristianLlanos** [comment]
Do you have a database which name is 53? Because that seems to be the error.

**Comment by CristianLlanos** [comment]
It might be a configuration mistake in `config/database.php` or your `.env` file. If that is not the case, could you please show me the output of "SHOW DATABASES" from your MySQL client.

**Comment by activemonkeys** [comment]
Thanks @CristianLlanos. Yes, for another project I had a database called 53. However the database for the project where your nice package is installed is named "rappa53". Temporarily removed the other database 53 and now it seems to work fine. Thanks for your quick reply. Much appreciated!

**Comment by CristianLlanos** [comment]
It seems kind of weird, right? MySQL didn't complain about that name when you created it, but now that we are making a query to get information from that database it squawks.

**Comment by CristianLlanos** [comment]
It think I've got an idea from "access violation". I believe your database user might not have permissions to query the other database (53).

**Comment by activemonkeys** [comment]
Yes, double checked my config/database.php and .env files. Nowhere there was a mention of a database called "53" only "rappa53". So it's strange that the database "53" was queried anyway. 

Well, it's solved for the moment. All new models (29!) have been created by your nice package. So a great time saver. Thank you very much. Hope others can benefit as well from your nice work. Again, much appreciated!

**Comment by CristianLlanos** [comment]
I'm happy you liked it. Don't hesitate to reach me if you encounter another issue :smile:

**Comment by CristianLlanos** [comment]
It turned out it was a bug in my query ([#5](https://github.com/reliese/laravel/issues/5)). It has been fixed, now :smile:

**Comment by pavagadhijatin** [comment]
It is not getting the database name which we have specified in .env file, instead it takes other database name and that DB name if we search in whole project, we can not find anywhere, don't know why this happen?
I need to delete the database from mysql which specified in error

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.`8` WHERE Table_type="BASE TABLE"' at line 1 (SQL: SHOW FULL TABLES FROM `laravel_blog_5`.`8` WHERE Table_type="BASE TABLE")
