### ISSUE TITLE
Asking for help

### ISSUE THREAD

**Issue by qeifar** [reliese/laravel#20]
I am putting Artisan:call to let it run "php artisan code:models"
But it shows this error. It like the php artisan code was undefined. How to solve it mates. I need your assistance. Thank You
![image](https://cloud.githubusercontent.com/assets/13729734/26084505/211f970a-3a0f-11e7-90d9-a27cf439fd4b.png)
![image](https://cloud.githubusercontent.com/assets/13729734/26084505/211f970a-3a0f-11e7-90d9-a27cf439fd4b.png)

There are no commands defined in the "php artisan code" namespace.

**Comment by CristianLlanos** [comment]
Did you register the service provider correctly under the `config/app.php` file?
```php
// ...
'providers' => [
    /*
     * Package Service Providers...
     */

    Reliese\Coders\CodersServiceProvider::class,
],
// ...
```

**Comment by CristianLlanos** [comment]
I haven't tried using it this way 🤔, though.

**Comment by CristianLlanos** [comment]
Why do you need to trigger this functionality that way? You can always [inject the factory](https://github.com/reliese/laravel/blob/master/src/Coders/Console/CodeModelsCommand.php#L44) `\Reliese\Coders\Model\Factory` and [play with the instance](https://github.com/reliese/laravel/blob/master/src/Coders/Console/CodeModelsCommand.php#L63) as you need.

**Comment by qeifar** [comment]
I am putting Artisan:call to the Controllers .. so that the newbie assistance(non-programmer) can easier execute the Model just by clicking the button T_T help me....

**Comment by qeifar** [comment]
Hi mates.. This link helped me 😃 
https://github.com/Torann/laravel-currency/issues/62
http://stackoverflow.com/questions/30011800/call-artisan-in-laravel-with-migratemake

Thank you again for your awesomeness work! 🥗 🥗 🍗

**Comment by CristianLlanos** [comment]
Cool! I'm glad you solved it! 👏
