### ISSUE TITLE
Missing dependency "irazasyed/larasupport"? 

### ISSUE THREAD

**Issue by linslin** [reliese/laravel#23]
I was only able to use this extension once I installed and configured https://github.com/irazasyed/larasupport

Is this dependency missing in your dependencies & configuration faq?

**Comment by CristianLlanos** [comment]
It shouldn't. I'll check this at the weekend.

**Comment by CristianLlanos** [comment]
I've tested the package in a fresh install of Laravel and everything works normally. This package doesn't need the dependency you mentioned.
