### ISSUE TITLE
 mkdir(): Invalid path

### ISSUE THREAD

**Issue by linslin** [reliese/laravel#24]
Getting the following error when running `php artisan code:models --table=sales_executive
`: 

```
[ErrorException]
mkdir(): Invalid path
```

My config file is present in `./config/models.php` and was created by CLI with:  `php artisan vendor:publish --tag=reliese-models`.

Debugging `$this->config` in `CodersServiceProvider` says:

```
class Reliese\Coders\Model\Config#194 (1) {
  protected $config =>
  NULL
}
```

Any ideas?

**Comment by linslin** [comment]
Btw. in the config file is a function used: `app_path()` but this function is not declared at all.

**Comment by linslin** [comment]
Debugging part 2 in `CodersServiceProvider.php`:
```
    protected function registerModelFactory()
    {
        $this->app->singleton(ModelFactory::class, function ($app) {

            var_dump($app->make('config')->get('models'));
           // NULL

//            return new ModelFactory(
//                $app->make('db'),
//                $app->make(Filesystem::class),
//                new Classify(),
//                new Config($app->make('config')->get('models'))
//            );
        });
    }
```

**Comment by CristianLlanos** [comment]
You might've forgot to run `php artisan vendor:publish --tag=reliese-models`

**Comment by linslin** [comment]
As i said, it did run it and the config file is present in `./config/models.php`

**Comment by CristianLlanos** [comment]
I've tried to replicate this problem in a fresh install of Laravel and everything works as expected. I don't have any ideas on why this is happening to you. `app_path` is a function declared by [Laravel itself](https://github.com/laravel/framework/blob/5.4/src/Illuminate/Foundation/helpers.php#L118).

**Comment by CristianLlanos** [comment]
Feel free to update this issue if you find more information about this behaviour.

**Comment by DamienBurkeJJ** [comment]
Same problem here. Fresh install of Laravel and this extension;

Running `php artisan vendor:publish --tag=reliese-models` results in...

```
Copied File [/vendor/reliese/laravel/config/models.php] To [/config/models.php]
Publishing complete.
```

Then `php artisan code:models` comes back with...

```
  [ErrorException]       
  mkdir(): Invalid path  
```
Looking at `laravel.log` shows that it is trying to do `mkdir('')` so it doesn't appear to be processing config/models.php correctly - `$app->make('config')` does not include a models section.

**Comment by DamienBurkeJJ** [comment]
Solved - needed a `php artisan config:clear` - worth adding to the readme

**Comment by CristianLlanos** [comment]
Great! Thanks for sharing the solution with us :) You can make a pull request to update the readme 👍

**Comment by devalexandre** [comment]
I try it, but in lumen don't have php artisan cache:clear

**Comment by kdutt1597** [comment]
composer create-project --prefer-dist laravel/laravel laravel "5.2.*"
[Error Exception]
mkdir(): Invalid Path

**Comment by CristianLlanos** [comment]
Have you tried clearing the config cache? https://github.com/reliese/laravel/issues/24#issuecomment-319414354

**Comment by renzocastillo** [comment]
> You might've forgot to run `php artisan vendor:publish --tag=reliese-models`

thanks Cristian!

**Comment by shrikantpardhi** [comment]
> Solved - needed a `php artisan config:clear` - worth adding to the readme

It worked for me. thanks
