### ISSUE TITLE
Typo in WhoDidIt referring to "udpated_by" instead of "updated_by"

### ISSUE THREAD

**Issue by NaLogo** [reliese/laravel#241]
Hey,

there is a typo in WhoDidIt, it refers to the field "udpated_by" instead of "updated_by". Line 43

`
public function updating(Eloquent $model){
        $model->udpated_by = $this->doer();
}
`

**Comment by NaLogo** [comment]
Opened a PR

https://github.com/reliese/laravel/pull/242

**Comment by finiteinfinity** [comment]
Fixed in #242
