### ISSUE TITLE
Deprecated "dates" property

### ISSUE THREAD

**Issue by pizavo** [reliese/laravel#255]
In Laravel 10.x Eloquent deprecated "dates" property has been removed and dates should be now put into "casts" property as with any other cast: [Changelog](https://laravel.com/docs/10.x/upgrade#model-dates-property)

We generate very many files from database and it would be real pain to update every single model and to change its properties according to this change.
Would it be possible to update this feature?

Thank you.

**Comment by finiteinfinity** [comment]
Hey @Pizavo, the v1.2.0 release fixes this very issue, which was released earlier today 👍 

https://github.com/reliese/laravel/releases/tag/v1.2.0
