### ISSUE TITLE
Enhancement: Column mapping needed

### ISSUE THREAD

**Issue by anil1712** [reliese/laravel#28]
Hi,

I have one large database which have 150+ tables and in most of the table fields has unstructured column naming like some have Snake case (with Uppercase) and some have Camel Cases. So I want to generate model classes in such a way that all the class attribute should be in camel cases and model class can refer some thing like 
<code>
@ColumnMapping ('USER_NAME') 
private userName;
</code>

Please suggest me some of the solution for the same. I got that column mapping idea from JPA (In Java Spring MVC framework)

Thanks,
Anil

**Comment by CristianLlanos** [comment]
I'm not sure whether [Laravel's Eloquent](https://laravel.com/docs/eloquent) support what you need 🤔 Maybe you can play with [snake_attributes](https://github.com/reliese/laravel/blob/master/config/models.php#L186).
