### ISSUE TITLE
Plural form of Child becomes Childrens

### ISSUE THREAD

**Issue by activemonkeys** [reliese/laravel#3]
Just came across a minor thing... 

In my project there is a table called "children". In the schema, the following foreign key is created: 

$table->foreign('individual_id')->references('id')->on('individuals')->onDelete('cascade');

The "child" model is created correctly with your script. However, in the "individual" model the following function is created: 

	public function childrens()
	{
		return $this->hasMany(\App\Models\Child::class);
	}

Have manually renamed "childrens" to "children" so no problem.

**Comment by CristianLlanos** [comment]
It seems the library I used to pluralize the table names add an 's' to the plural form of children (of course it does not have a plural form). I thought It was smart enough as not to add an 's'. I've made a quick fix for this. Thanks!
