### ISSUE TITLE
Generating model name problems

### ISSUE THREAD

**Issue by zongmi** [reliese/laravel#34]
The table name user_data generates UserDatum.php instead of UserData.php
Although I know my name has a problem, but it should not be so

**Comment by CristianLlanos** [comment]
The naming convention for models is that they should be in singular and their tables in plural. My algorithm enforces that convention when possible. Data's singular form appears to be `datum`, so I don't see the problem. http://www.wordreference.com/definition/datum

**Comment by zongmi** [comment]
Well, I see
