### ISSUE TITLE
Laravel 5.5

### ISSUE THREAD

**Issue by williamnwogbo** [reliese/laravel#35]
I doesnt generate the models in Laravel 5.5, check it out

**Comment by CristianLlanos** [comment]
Do you get an error message?

**Comment by vishalag991** [comment]
I am getting this error for Laravel 5.5 
[RuntimeException]                                                            
  There is no Schema Mapper registered for [Larapack\DoctrineSupport\Connectio  
  ns\MySqlConnection] connection.

**Comment by BryanJames16** [comment]
I'm using Laravel 5.5 with the latest version of this package. Everything seems to be working fine for me.

**Comment by MrAntunes** [comment]
Same issue, am I missing something?

laravel.log
`[2018-01-08 15:28:37] local.ERROR: There is no Schema Mapper registered for [Larapack\DoctrineSupport\Connections\MySqlConnection] connection. {"exception":"[object] (RuntimeException(code: 0): There is no Schema Mapper registered for [Larapack\\DoctrineSupport\\Connections\\MySqlConnection] connection. at D:\\WORKING\\XXXXX\\vendor\
eliese\\laravel\\src\\Meta\\SchemaManager.php:53)
[stacktrace]
#0 D:\\WORKING\\XXXXX\\vendor\
eliese\\laravel\\src\\Meta\\SchemaManager.php(44): Reliese\\Meta\\SchemaManager->boot()
#1 D:\\WORKING\\XXXXX\\vendor\
eliese\\laravel\\src\\Coders\\Model\\Factory.php(100): Reliese\\Meta\\SchemaManager->__construct(Object(Larapack\\DoctrineSupport\\Connections\\MySqlConnection))
#2 D:\\WORKING\\XXXXX\\vendor\
eliese\\laravel\\src\\Coders\\Console\\CodeModelsCommand.php(69): Reliese\\Coders\\Model\\Factory->on('mysql')
#3 [internal function]: Reliese\\Coders\\Console\\CodeModelsCommand->handle()
#4 D:\\WORKING\\XXXXX\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(29): call_user_func_array(Array, Array)
#5 D:\\WORKING\\XXXXX\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#6 D:\\WORKING\\XXXXX\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#7 D:\\WORKING\\XXXXX\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#8 D:\\WORKING\\XXXXX\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(183): Illuminate\\Container\\Container->call(Array)
#9 D:\\WORKING\\XXXXX\\vendor\\symfony\\console\\Command\\Command.php(252): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#10 D:\\WORKING\\XXXXX\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#11 D:\\WORKING\\XXXXX\\vendor\\symfony\\console\\Application.php(936): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#12 D:\\WORKING\\XXXXX\\vendor\\symfony\\console\\Application.php(240): Symfony\\Component\\Console\\Application->doRunCommand(Object(Reliese\\Coders\\Console\\CodeModelsCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#13 D:\\WORKING\\XXXXX\\vendor\\symfony\\console\\Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#14 D:\\WORKING\\XXXXX\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#15 D:\\WORKING\\XXXXX\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(121): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#16 D:\\WORKING\\XXXXX\\artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 {main}
"} `

My connection to DB don't use the standard port... (.env) ["laravel" it's working fine]
`DB_CONNECTION=mysql
DB_HOST=192.168.1.2
DB_PORT=7575
DB_DATABASE=XXXXX
DB_USERNAME=XXX
DB_PASSWORD=XXX`

Also, I'm testing voyager (https://github.com/the-control-group/voyager) but I don't think it'll interfere...

**Comment by CristianLlanos** [comment]
I believe it's because your project is using Larapack. It seems this package is not compatible with Larapack. :disappointed:

**Comment by MrAntunes** [comment]
Confirmed! I rolled back to a previous version without Voyager (it's using Larapack?) and now I can generate models.

PS: Although the generation takes some time (comparing to others generators), for a simple table it took ~43 min. I don't think this is how it would be supposed, probably one more issue with my project not being "fresh". Later I'll try with a clean laravel install.

**Comment by CristianLlanos** [comment]
Wow! :thinking: It shouldn't take that long.

**Comment by JavierSolis** [comment]
I also use Voyager, reviewing the file "SchemaManager", I understand that the conection that it uses is like an interface, so in theory it should work adding it to the list, so as not to return to the previous version, it worked for me to add Larapack in its list of , in the "SchemaManager.php" file


```
namespace Reliese\Meta;

use ArrayIterator;
use RuntimeException;
use IteratorAggregate;
use Illuminate\Database\MySqlConnection;
use Illuminate\Database\ConnectionInterface;
use Reliese\Meta\MySql\Schema as MySqlSchema;

class SchemaManager implements IteratorAggregate
{
    /**
     * @var array
     */
    protected static $lookup = [
        MySqlConnection::class => MySqlSchema::class,
       /**ADD THIS LINE **/
        \Larapack\DoctrineSupport\Connections\MySqlConnection::class => MySqlSchema::class,
    ];

    /**
     * @var \Illuminate\Database\ConnectionInterface
     */
    private $connection;
....
}
```

then run **php artisan code: models** and it worked.

**Comment by trepmag** [comment]
With octobercms we need also to alter this SchemaManager:
```
class SchemaManager implements IteratorAggregate
{
    protected static $lookup = [
        MySqlConnection::class => MySqlSchema::class,
       /**ADD THIS LINE **/
        \October\Rain\Database\Connections\MySqlConnection::class => MySqlSchema::class,
    ];
    ...
}
```
