### ISSUE TITLE
Add option to use space instead of tabs for indenting

### ISSUE THREAD

**Issue by delmicio** [reliese/laravel#36]
Hi, files generated are indented with tabs instead of spaces.

¿could you add and option to change this?

**Comment by CristianLlanos** [comment]
I'm open for pull requests :)

**Comment by delmicio** [comment]
Ok, I think I should add a new option and checked if true in 
https://github.com/reliese/laravel/blob/master/src/Coders/Model/Factory.php#L148
```PHP
$file = preg_replace('/\t+/', '    ', $file);
```
I'll try it later

**Comment by delmicio** [comment]
@CristianLlanos the PR #37 for this issue was sent

**Comment by delmicio** [comment]
@CristianLlanos is there anything else needed for merging?

**Comment by CristianLlanos** [comment]
Thanks for contributing. I've merged your PR, so I'm closing this issue.
