### ISSUE TITLE
Add a destination directory option for generated model 

### ISSUE THREAD

**Issue by bhargavjoshi** [reliese/laravel#4]
Hey, this is an excellent package. Thank you for taking time to make this. 

I use a little different kind of directory structure.  Refer to the example given below.

```
- app
    - Domain
        - User
            - User.php (file generate by your package)
            - Base (folder generate by your package)
                - User.php (file generate by your package)
        - Role
            - Role.php (file generate by your package)
                - Base (folder generate by your package)
                    - Role.php (file generate by your package)
```

So can we add and one more argument to the command to override the config file to generate in the following structure? 

`php artisan code:models --table=users  --src="Domain/User"`

**Comment by CristianLlanos** [comment]
Yes, you can accomplish this structure, but all you need to do is place the overridings within `config/models.php` file like this:

```php
'database' => [
    'users' => [
        'path' => app_path('Domain/User'),
        'namespace' => 'App/Domain/User',
    ],
    'roles' => [
        'path' => app_path('Domain/Role'),
        'namespace' => 'App/Domain/Role',
    ],
]
```
I made this intentionally, so you don't have to write the path and the namespace for your model every time you generate them.

**Comment by CristianLlanos** [comment]
The thing is, I just want us to write `php artisan code:models` and be done with it.

**Comment by bhargavjoshi** [comment]
Ok. This also works thanks 🙂 👍

**Comment by CristianLlanos** [comment]
Corrected the namespace in the example I provided. I forgot to use backslashes instead of slashes.

Since it might be very common to name the model directory and the model namespace similarly what do you think of having something like:
```php
'*' => [
    'base_namespace' => 'App',
    'base_path' => app_path(),
    //... defaults
],

'specific_database' => [
    'users' => [
        'namespace' => 'Domain/User',
    ],
    'roles' => [
        'namespace' => 'Domain/Role',
    ],
],
```

**Comment by bhargavjoshi** [comment]
I like this one more
 
```
'database' => [
    'users' => [
        'path' => app_path('Domain/User'),
        'namespace' => 'App\Domain\User',
    ],
    'roles' => [
        'path' => app_path('Domain/Role'),
        'namespace' => 'App\Domain\Role',
    ],
],
```

**Comment by CristianLlanos** [comment]
Perhaps, that might be a little confusing. I suppose it's not that bad to explicitly declare the model path along with the model namespace

 I'm glad you liked my package, btw. Thanks for your feedback. Please don't hesitate to reach me if you encounter any issues :-)

**Comment by bhargavjoshi** [comment]
I am so happy, this makes life so much easier, you just run one command all set. 
Thank you for making this wonderful package :)

**Comment by CristianLlanos** [comment]
Don't forget to tell your friends :smile:

**Comment by CristianLlanos** [comment]
Would you mind if I use your example when I write some documentation for this feature?

**Comment by bhargavjoshi** [comment]
not at all. Please go ahead.

**Comment by CristianLlanos** [comment]
Thanks!
