### ISSUE TITLE
Inheriting Authenticatable

### ISSUE THREAD

**Issue by hassoon3** [reliese/laravel#47]
Hi,

The user model (by default) inherits `Illuminate\Foundation\Auth\User as Authenticatable`, however, the generated models inherit the `Reliese\Database\Eloquent\Model`.

In the current version we are unable to use both. Please suggest a solution to use both or add a feature to the package to solve it.

This package is a very good package! I really like.

Regards,

**Comment by CristianLlanos** [comment]
This is feasible through the config file. You should add an entry for your `user` table to specify its inheritance. Given your database name is `my_database` you should add the following to your `config/models.php` file:

```php
return [
    // ....

    'my_database' => [
        'user' => [
            'parent' => 'Illuminate\Foundation\Auth\User',
        ],
    ],

];
```
That should do the work.

**Comment by hassoon3** [comment]
Thanks for the quick response.

In fact, the provided configuration WILL result in a `User` model inherting `Illuminate\Foundation\Auth\User` while other models inherit the `Reliese\Database\Eloquent\Model`. In which case, the `User` model lacks the functions of the `Reliese\Database\Eloquent\Mode`.

Won't that cause problems to the `User` model?

**Comment by CristianLlanos** [comment]
There won't be any problem at all. I created `Reliese\Database\Eloquent\Model` as an example. You can use whatever you want/need as long as it inherits `Illuminate\Database\Eloquent\Model`, otherwise you won't be able to use the class as an ORM model.

**Comment by hassoon3** [comment]
That answers my question. Thanks.

**Comment by IManAsap** [comment]
Hello

My table has the name 'users',

If I use the following configuration

    ...
    'transpeapppla' => [

        'users' => [
            'parent' => Illuminate\Foundation\Auth\User::class,
        ],
    ]
    ...

I get the following model

    class User extends User
    {
        protected $table = 'users';
        ...
    }

With the following logical message

    Class 'App\Models\Base\User' not found

Is that a bug?
