### ISSUE TITLE
Some Foreignkeys and Primary keys are missing in fillables

### ISSUE THREAD

**Issue by sridamagit** [reliese/laravel#48]
As they are missing, not able to create rows with missing columns

Can anyone tell us how to solve this problem

**Comment by CristianLlanos** [comment]
Would you mind giving some examples in order to reproduce this error?

**Comment by CristianLlanos** [comment]
Without any examples no one would be able to fix this.

**Comment by CristianLlanos** [comment]
I'm closing this issue since there is no information on how to replicate the error.
