### ISSUE TITLE
Error running 'php artisan code:models' mysql query appears to be missing backticks

### ISSUE THREAD

**Issue by greenbeemedia** [reliese/laravel#5]
The command kicked out with the error messages below.  It appears that the SQL statement "SHOW FULL COLUMNS FROM dcdb.active-web-products" whereas it should be "SHOW FULL COLUMNS FROM \`dcdb\`.\`active-web-products\`"

**ERRORS:**

[Illuminate\Database\QueryException]
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-web-products' at line 1 (SQL: SHOW FULL COLUMNS FROM dcdb.active-web-products)                                                                                                                 

[Doctrine\DBAL\Driver\PDOException]                                                                                              
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-web-products' at line 1

[PDOException]                                                                                                                   
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-web-products' at line 1

**Comment by CristianLlanos** [comment]
Thanks, I'm going to check it.

**Comment by CristianLlanos** [comment]
I've added the missing backticks. It should work now :) Thanks for your feedback.
