### ISSUE TITLE
Table Naming conventions

### ISSUE THREAD

**Issue by hassoon3** [reliese/laravel#50]
This is a wonderful package. But through my research in the code - which came in response to the problem that some belongsToMany relations were not being generated properly - I learned that the you've assumed some naming conventions for pivot tables for the code to work correctly.

We would appreciate it if those conventions are published in the README.

Regards,

**Comment by CristianLlanos** [comment]
Those naming conventions are based on Laravel's source code. However, I'm not sure Laravel has documented them :thinking:
I'm open for pull requests, if you'd like to that information to the README :)

**Comment by hassoon3** [comment]
Ok. Thanks Cristian.

**Comment by Grummfy** [comment]
for information : https://laravel.com/docs/5.5/eloquent#eloquent-model-conventions

**Comment by CristianLlanos** [comment]
Thanks @Grummfy 👍
