### ISSUE TITLE
When performing the generation of models you may want to take some of them

### ISSUE THREAD

**Issue by andrey-helldar** [reliese/laravel#52]
Example:
A package can exclude selected tables:
```
'except'       => [
    'migrations',
],
```

But there is a situation that the database contains many tables (for example, 197 like mine), and it is necessary to generate models for only four of them.

I suggest adding the "only" key to define the list of tables for which the models will be generated.

**Comment by CristianLlanos** [comment]
:sweat_smile: You got me!
I'm open for Pull Requests. It'd be nice to accept your contribution :)

**Comment by andrey-helldar** [comment]
I created a PR :)

**Comment by Grummfy** [comment]
perhaps this issue can now be closed?
