### ISSUE TITLE
Remove {{date}} from model template

### ISSUE THREAD

**Issue by AcoustickSan** [reliese/laravel#54]
Can you remove this from model template? Because sometimes it causes problems with Git and other VCS

**Comment by CristianLlanos** [comment]
I think this is a good idea. You are welcome to open a pull request with the improvements if you don't mind :)

**Comment by tpaksu** [comment]
Hi, do you plan to create a new release including this update? I need this because everytime I run code:models, models without changes also need to be pushed to the repository. I don't want to undo/discard/reset every model on git when I change only one.

**Comment by CristianLlanos** [comment]
If you need this feature, you can import the dev-master version of the package and you can take advantage of it before I make the release.
