### ISSUE TITLE
HasOne relationship...

### ISSUE THREAD

**Issue by anurbol** [reliese/laravel#63]
Hello again! Let's say i have two models: 
**Human** and **Brain**
it is one-to-one (**hasOne**) relationship. 

Currently code:models generates 
`	public function brains()
	{
		return $this->hasMany(\App\Brain::class);
	}
`
instead of
`	public function brain()
	{
		return $this->hasOne(\App\Brain::class);
	}
`
in Human model.

Is there any way, i can tell the library to use hasOne instead of hasMany? I didn't find any. I also wanted to make it on my own (and create pull request), but then I looked at the code. It is beautiful. But too complex for me, no matter how hard i tried to understand it :-( . Maybe you can tell direction (location of code to edit) and i can make it?

P.S. Only then, when i've looked at your code, i have really understood, how much work was made by you. Have my big respect.

**Comment by CristianLlanos** [comment]
This is happening because the `brain` table has a `human_id` field which doesn't have unique index. This means that your database allows for a human to have one or many brains ;) You should add a UNIQUE KEY constraint to your `human_id` field and my package will fix the code :)

**Comment by anurbol** [comment]
Wow! Great! ...I thinked at first :-) Though, it didnt' work. Well, it didn't work wwithout little fix in your code. I am going to create a pull request right now... Please review it asap!

**Comment by CristianLlanos** [comment]
Sorry for the delay. I left you a comment in the PR.
