### ISSUE TITLE
Problem when passing array to property with json cast

### ISSUE THREAD

**Issue by phiterf** [reliese/laravel#64]
I'm getting this error when I try to pass an array to a model property that is cast as json.

The generator made the entire class by itself, and those are the field generated stuff:

```
/*
* @property array $extra_fields
*/

protected $casts = [
    'extra_fields' => 'json'
];
```
Exception:

![image](https://user-images.githubusercontent.com/12252332/34442458-7bced6be-eca9-11e7-9f3f-a7a0df93f820.png)

The tool created the model adding this use clause:

`use Reliese\Database\Eloquent\Model as Eloquent;`

When I switched it to the Illuminate class, it worked.

`use Illuminate\Database\Eloquent\Model as Eloquent;`

Can this be fixed or  is there a way to use Illuminate classes instead of classes from the Reliese namespace?

**Comment by CristianLlanos** [comment]
Sure, you can use `Illuminate\Database\Eloquent\Model` as the default parent class. You just need to change it in the config file (https://github.com/reliese/laravel/blob/master/config/models.php#L55)

**Comment by phiterf** [comment]
Oh I see, I did not notice that one. Thanks for the reply. I'll update my code first thing tomorrow. Thank you!
