### ISSUE TITLE
Merge Casting with BaseModel and Model

### ISSUE THREAD

**Issue by hamid09430** [reliese/laravel#72]
Allow user to add Custom Casting on UserModel File that will be merged with BaseModel casting attribute.
because some time we need to add our own casting attributes and when we recompile our models then that casting attribute are also overiden.

i have achived it by defining custom Casting array in Model and then merge it with BaseModel casting array in BaseModel contructor

**Comment by VladimirBerdnik** [comment]
Doesn't **Casts** section in config.php helps? 
https://github.com/reliese/laravel/blob/master/config/models.php#L253

**Comment by hamid09430** [comment]
i want to cast something that is not column but is a relation like Laravel withCount('has_liked' ,......)
in this case it will give me count in integer but i want it in bool so what i need to do is casting.
as you know has_liked is not a column of database so we need to add it explicitly.

**Comment by VladimirBerdnik** [comment]
can't  **getHasLikedAttribute()** Laravel's accessor help? Just suggestion as workaround

**Comment by hamid09430** [comment]
it will but putting it in casting array looks more easy and meaningfull.

**Comment by VladimirBerdnik** [comment]
And your suggestion is to allow configure custom castings for one or many possible models? Because UserModel is common case and some projects can be created without this model.

**Comment by hamid09430** [comment]
hey can u provide option for the user to select either he want fillable , casting, hidden attributes in UserModel file or BaseModel file ?
it will provide a great flexibility to users.
However by defaults you can set the current settings.

**Comment by CristianLlanos** [comment]
Did you find a workaround for this? 🤔

**Comment by hamid09430** [comment]
yes
