### ISSUE TITLE
Issue with model names

### ISSUE THREAD

**Issue by camiloclc** [reliese/laravel#73]
First of all, amazing work!

I'm having a bit of a problem with how some model names end up differently as to how they are defined in the database. The app I want to migrate to Laravel is developed in portuguese, and database table names are also in portuguese. I have around 100 tables and growing.

It seems the `getRecordName` method in `Reliese\Coders\Model\Model` calls `Str::singular`, which doesn't always play nice with non english words. Words like `agencia` (_agency_) turn into `agencium`, `pais` (_country_) turn into `pai` (_father_), etc., so I'm ending up with model names that don't follow Laravel's conventions when they would if the original name was used. Some of these singular forms don't make sense at all or they completely change the meaning of the word.

It normally wouldn't be a problem for me to change it manually, but this application is being actively developed, so I'll need to generate models periodically, and it's affecting several models.

Is there a way to make this configurable?

**Comment by camiloclc** [comment]
By the way, something similar happens to the pluralization of hasMany relationships, but I'm well aware that in this case there's not much that can be done, they'll have to be changed manually when  this migration is mature enough.

**Comment by CristianLlanos** [comment]
Wow! I'm not sure how to help your with this. You're having pluralization problems because both `Str::singular` and `Str::plural` support English words only. Laravel's `Str` helper class is based on [Doctrine's Inflector](https://github.com/doctrine/inflector), btw.

**Comment by camiloclc** [comment]
Yes, I've seen it! What I meant was creating a setting in `config/models.php` that would be turned on by default, but if I turned it off, `Str::singular` wouldn't be called when determining what a Model's name should be. Because my database is already following the table naming conventions, turning the setting off would actually make the generated names stay true to that.

As for the relationship names that go through `Str::plural`, I don't see an easy solution. Even if pluralization is kind of screwing them up a bit, either way I'll have to fix them up manually eventually. Maybe making the call to `Str::plural` configurable might help developers that use other languages. More info on [unicode.org](http://www.unicode.org/cldr/charts/29/supplemental/language_plural_rules.html) (search for no plural differences), [MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localization_and_Plurals) (search for pluralRule=0).

**Comment by CristianLlanos** [comment]
Supporting variations of any possible language seems like a nightmare for a package. I'm not planning on going down that road. I suggest using English names in our databases, our source code and translations for user facing strings. If for some reason we find pluralization errors we should report it and/or help with PR to the Doctrine's package

**Comment by zapcriativo** [comment]
@camiloclc  

Hello,

Where did you make the change to bring the name into the plural?

**Comment by herquiloidehele** [comment]
You can try to return the value that represents the table name before the return of this function.

![screenshot 2019-01-30 03 08 50](https://user-images.githubusercontent.com/23740775/51951320-d879a800-243c-11e9-87d1-469e53c39c6a.png)
