### ISSUE TITLE
 There are no commands defined in the "code" namespace.  

### ISSUE THREAD

**Issue by josesuarezcordova** [reliese/laravel#83]
Hi, I tried to run the command
`php artisan code:models`

but return that message

` There are no commands defined in the "code" namespace.  `

I just followed the steps to install and setup the plugin and seems ok,could you give me some clues about it ? thanks!

**Comment by VladimirBerdnik** [comment]
Hi! Is service provider was added according to [configuration](https://github.com/reliese/laravel#configuration) section?
Maybe your config cached and need to clear config cache with `php artisan config:clear` command

**Comment by josesuarezcordova** [comment]
HI, thanks for your answer, actually something left but now I got this 

`joses-MacBook-Pro:vero_cms josesuarez$ php artisan code:models

In Model.php line 684:
                                                                              
  count(): Parameter must be an array or an object that implements Countable`

some clues?

**Comment by VladimirBerdnik** [comment]
Is there primary key in your table?

**Comment by josesuarezcordova** [comment]
ok I got it, some tables dont have Primary key setup, I did for one of them and work fine, I'll do for the rest and try again , excellent library ! thanks!

**Comment by VladimirBerdnik** [comment]
You're welcome!)
p.s. it is not my library, I just seen your question)

**Comment by CristianLlanos** [comment]
There is an attempt to solve this with PR #93. Hopefully it works for you guys.
