### ISSUE TITLE
Problems with JSON casts

### ISSUE THREAD

**Issue by staudenmeir** [reliese/laravel#88]
Having JSON attributes causes problems:

    protected $casts = [
        'foo' => 'array',
        'bar' => 'json'
    ];

[`Model::setAttribute()`](https://github.com/reliese/laravel/blob/master/src/Database/Eloquent/Model.php#L47) checks for `toArray()` or `toJson()` and uses them, which leads to strange results (https://github.com/laravel/framework/issues/24053) or doesn't work (https://github.com/reliese/laravel/issues/64).

A possible workaround is using the equivalent `object` or `collection` casts.

**Comment by staudenmeir** [comment]
I wasn't the one having the problem, I just reported it.

**Comment by CristianLlanos** [comment]
Thanks!
