### ISSUE TITLE
RunTimeException exception when trying to generate models from Postgres database

### ISSUE THREAD

**Issue by tandasima** [reliese/laravel#9]
Hi thank you for this tool.

I am experiencing an issue though. When I run php artisan code:models I get the following RunTimeException exception

There is no Schema Mapper registered for [Illuminate\Database\PostgresConnection] connection.

I am using Postgres database and my connection looks like

'pgsql' => [
            'driver' => 'pgsql',
            'host' => 'localhost',
            'port' => '5432',
            'database' => 'test',
            'username' => 'postgres',
            'password' => '',
            'charset' => 'utf8',
            'prefix' => '',
            'schema' => 'public',
            'sslmode' => 'prefer',
        ],

Thank you.

**Comment by tandasima** [comment]
Looks like it only supports MySQL.

**Comment by CristianLlanos** [comment]
I'm sorry. I haven't had time to add support for other databases yet :( But I'm planning to do it.
