### ISSUE TITLE
Check for countable throws exception

### ISSUE THREAD

**Issue by zainbsse2037** [reliese/laravel#90]
hasCustomPrimaryKey() function got error when $this->primaryKeys->columns are not countable in reliese\laravel\src\Coders\Model\Model.php
i have fixed it
if you want you can add it in your src

if(isset($this->primaryKeys->columns) && is_array($this->primaryKeys->columns))
 {
            return count($this->primaryKeys->columns) == 1 &&
            $this->getPrimaryKey() != $this->getDefaultPrimaryKeyField();
}
else
{
       return false;
 }

Thanks
Regards
Zain Ul Abideen

**Comment by CristianLlanos** [comment]
I've accepted PR #93 which attempts to solve this problem.
