### ISSUE TITLE
Command fails if a table doesn't have AI PK column

### ISSUE THREAD

**Issue by maurotikus** [reliese/laravel#92]
php artisan code:models -v

> ErrorException  : count(): Parameter must be an array or an object that implements Countable
>
>  at /home/aforero/public_html/opx/vendor/reliese/laravel/src/Coders/Model/Model.php:684
>    680|      * @return bool
>    681|      */
>    682|     public function hasCustomPrimaryKey()
>    683|     {
>  > 684|         return count($this->primaryKeys->columns) == 1 &&
>    685|                $this->getPrimaryKey() != $this->getDefaultPrimaryKeyField();
>    686|     }
>    687| 
>    688|     /**
>
>  Exception trace:
>
>  1   count()
>      /home/aforero/public_html/opx/vendor/reliese/laravel/src/Coders/Model/Model.php:684
>
>  2   Reliese\Coders\Model\Model::hasCustomPrimaryKey()
>      /home/aforero/public_html/opx/vendor/reliese/laravel/src/Coders/Model/Factory.php:309
>
>  3   Reliese\Coders\Model\Factory::body(Object(Reliese\Coders\Model\Model))
>      /home/aforero/public_html/opx/vendor/reliese/laravel/src/Coders/Model/Factory.php:233
>
>  4   Reliese\Coders\Model\Factory::fillTemplate("<?php
>
>/**
> * Created by Reliese Model.
> * Date: Tue, 15 May 2018 17:30:37 +0000.
> */
>
>namespace App\Models;
>
>use Reliese\Database\Eloquent\Model as Eloquent;
>
>/**
> * Class PasswordReset
> * 
> * @property string $email
> * @property string $token
> * @property \Carbon\Carbon $created_at
> *
> * @package App\Models
> */
>class PasswordReset extends Eloquent
>{
>{{body}}
>}
>", Object(Reliese\Coders\Model\Model))
>      /home/aforero/public_html/opx/vendor/reliese/laravel/src/Coders/Model/Factory.php:148
>
>  5   Reliese\Coders\Model\Factory::create("opxdb", "password_resets")
>      /home/aforero/public_html/opx/vendor/reliese/laravel/src/Coders/Model/Factory.php:118
>
>  6   Reliese\Coders\Model\Factory::map("opxdb")
>      /home/aforero/public_html/opx/vendor/reliese/laravel/src/Coders/Console/CodeModelsCommand.php:69
>
>  7   Reliese\Coders\Console\CodeModelsCommand::handle()
>      /home/aforero/public_html/opx/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29
>
>  8   call_user_func_array([])
>      /home/aforero/public_html/opx/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29
>
>  9   Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
>      /home/aforero/public_html/opx/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:87
>
>  10  Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Object(Closure))
>      /home/aforero/public_html/opx/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:31
>
>  11  Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), [])
>      /home/aforero/public_html/opx/vendor/laravel/framework/src/Illuminate/Container/Container.php:564
>
>  12  Illuminate\Container\Container::call()
>      /home/aforero/public_html/opx/vendor/laravel/framework/src/Illuminate/Console/Command.php:183
>
>  13  Illuminate\Console\Command::execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
>      /home/aforero/public_html/opx/vendor/symfony/console/Command/Command.php:252
>
>  14  Symfony\Component\Console\Command\Command::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
>      /home/aforero/public_html/opx/vendor/laravel/framework/src/Illuminate/Console/Command.php:170
>
>  15  Illuminate\Console\Command::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
>      /home/aforero/public_html/opx/vendor/symfony/console/Application.php:865
>
>  16  Symfony\Component\Console\Application::doRunCommand(Object(Reliese\Coders\Console\CodeModelsCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
>      /home/aforero/public_html/opx/vendor/symfony/console/Application.php:241
>
>  17  Symfony\Component\Console\Application::doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
>      /home/aforero/public_html/opx/vendor/symfony/console/Application.php:143
>
>  18  Symfony\Component\Console\Application::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
>      /home/aforero/public_html/opx/vendor/laravel/framework/src/Illuminate/Console/Application.php:89
>
>  19  Illuminate\Console\Application::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
>      /home/aforero/public_html/opx/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:122
>
>  20  Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
>      /home/aforero/public_html/opx/artisan:37

This table in particular is created by the Passport package, but its structure is as follows:

```
CREATE TABLE `password_resets` (
    `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
    `token` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
    `created_at` timestamp NULL DEFAULT NULL,
    KEY `password_resets_email_index` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```

**Comment by jefhar** [comment]
Came here to report this. @maurotikus beat me by 3 hours.

**Comment by sajjadbandari** [comment]
@maurotikus your issue title saved my day, thank you 👍
